name: test-cicd

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17.6'

      - name: Install dependencies
        run: make setup

      - name: Build and Test
        run: make test

